version: '3'

services:
  rabbitmq:
    image: rabbitmq
    expose:
      - "5672" 
    networks:
      - rabbit

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-policydemic-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms3072m -Xmx3072m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data_01:/usr/share/elasticsearch/data
      - /mnt/data_storage/snapshots:/usr/share/elasticsearch/snapshots
    networks:
      - elastic

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-policydemic-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms3072m -Xmx3072m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data_02:/usr/share/elasticsearch/data
      - /mnt/data_storage/snapshots:/usr/share/elasticsearch/snapshots
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.12.0
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200"]'
    links:
     - "es01:es01"
     - "es02:es02"
    networks:
      - elastic

  policydemic:
    build: .
    tty: true
    container_name: policydemic_app
    volumes:
      - /mnt/data_storage/policydemic_data:/opt/policydemic_data
      - ./policydemic:/opt/app/
    ports:
      - "5555:5555"
      - "80:80"
      - "443:443"
    expose:
      - "5672"
    depends_on:
      - rabbitmq
      - es01
      - es02
    networks:
      - elastic
      - rabbit
    links:
      - "rabbitmq:rabbitmq"
      - "es01:elastic"
    entrypoint:
      - /opt/entrypoint.sh

volumes:
  es_data_01:
    driver: local
  es_data_02:
    driver: local

networks:
  elastic:
    driver: bridge
  rabbit:
    driver: bridge
